### ISSUE TITLE
[core] `DashboardLayout` theme overrides issues

### ISSUE THREAD

**Issue by bharatkashyap** [mui/toolpad#4066]
1. Many styles from List and ListItem not being applied to Toolpad Core layout

> Styling seems to be working differently from the current Material UI components.In the custom theme, there are many styles for List and ListItem , but these aren’t being applied to the layout.

| [Toolpad Core Theme app](https://github.com/zanivan/toolpad-core-theme) | [Material UI Dashboard Template App](https://github.com/mui/material-ui/tree/master/docs/data/material/getting-started/templates/dashboard) |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/a6d404e2-192a-432a-b770-4e471904e639" width=400> | <img src="https://github.com/user-attachments/assets/d5e1589e-aa4b-46ec-a84e-5912b604f116" width=300 /> |

2. Custom theme breaking for `focus` and `active` states
> The custom theme seems to be applied in most of the UI, but in some states such as focus and active are acting weird:

![image](https://github.com/user-attachments/assets/87f18640-1873-4180-a052-16bca0498f35)
![image](https://github.com/user-attachments/assets/063fe03d-c108-4691-b816-93f0be052862)

- Link to [full feedback](https://www.notion.so/mui-org/Toolpad-Core-review-58ef743943104bfbb1d57794c74fc0c0?pvs=4#48a0e82aa366477a9891db550d3d85bd)

**Search keywords**:

**Comment by apedroferreira** [comment]
Some of these styles are set so that the components look nicer by default, I expected them to be easily overridable in the theme.
If they're not that straightforward to override we can try maybe not setting some of them, not sure - maybe the app will still look ok enough with the default styles, but would have to check.
Otherwise I guess the template theme might be missing some styles that are needed to be used on top of Toolpad Core.
